services:
  easystreams:
    build: .
    container_name: easystreams
    ports:
      - "7000:7000"
    environment:
      - PORT=7000
      - NODE_ENV=production
      - VERBOSE_LOGS=0
      - QUIET_PROVIDER_LOGS=1
      # FlareSolverr viene gestito internamente dall'addon
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped
